---
abstract: 'Perl class for reading a graph from TGF format with CSV labeling.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  Encode: 0
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.07
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Graph-Reader-TGF-CSV
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Error::Pure: 0.16
  Graph::Reader::TGF: 0.01
  Text::CSV: 0
  perl: 5.6.2
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Graph-Reader-TGF-CSV
  homepage: https://github.com/tupinek/Graph-Reader-TGF-CSV
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Graph-Reader-TGF-CSV
version: '0.02'
